### ISSUE TITLE
3D plots not working on RTFD

### ISSUE THREAD

**Issue by jaidevd** [scikit-signal/pytftb#89]
All examples containing 3D plots fail with this error:

```python
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytftb/envs/latest/local/lib/python2.7/site-packages/sphinx_gallery/gen_rst.py", line 417, in execute_script
    exec(code_block, example_globals)
  File "<string>", line 18, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytftb/envs/latest/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1268, in gca
    return self.add_subplot(1, 1, 1, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytftb/envs/latest/local/lib/python2.7/site-packages/matplotlib/figure.py", line 958, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytftb/envs/latest/local/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 78, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 91, in __init__
    *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytftb/envs/latest/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 436, in __init__
    self.cla()
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1045, in cla
    Axes.cla(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytftb/envs/latest/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 897, in cla
    self.grid(self._gridOn, which=rcParams['axes.grid.which'])
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1256, in grid
    self._draw_grid = maxes._string_to_bool(b)
AttributeError: 'module' object has no attribute '_string_to_bool'
```

**Comment by PeeyushAgg** [comment]
Can you specify what actually you mean by RTFD. Is it Robust Time-Frequency Decomposition or Something else??????

**Comment by jaidevd** [comment]
@PeeyushAgg It's http://readthedocs.org
